# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a6e2c7e46a7dc6c9d08c39c97bd57ff1cf1d8d217e4c122b68dae494fe32975e428c8c84933cd689a08b68e616b0e6122f151be6f90b467616e7179c953f655a

test:
  secret_key_base: c544cf6e9a8b8f350748dae8578bd3141bc8061b601d10586a2e75c251bfed2ca50bb9fd7065416c82d6602c9f72aa37105653894058c76e3b07e5c8756f0840

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
